"""Comprehensive AI Model Data for Registry Initialization.

This file contains detailed model definitions for all supported providers.
Used to seed the database with up-to-date model information.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

from src.models.ai_model import ModelCategory, ModelTier


# ==================== OpenAI Models ====================
OPENAI_MODELS: list[dict[str, Any]] = [
    # GPT-5 Family (2025)
    {
        "model_id": "gpt-5.2",
        "name": "gpt-5.2",
        "display_name": "GPT-5.2",
        "aliases": ["gpt-5-latest", "gpt5"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Most capable GPT model with advanced reasoning and multimodal understanding.",
        "description": "GPT-5.2 is OpenAI's flagship model offering state-of-the-art performance across reasoning, coding, creative writing, and analysis. Features enhanced chain-of-thought reasoning, superior instruction following, and native multimodal capabilities.",
        "best_for": ["Complex reasoning", "Code generation", "Creative writing", "Data analysis", "Multi-step tasks"],
        "context_window": 256000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("15.00"),
        "output_price_per_1m": Decimal("60.00"),
        "badge": "FLAGSHIP",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "gpt-5.1",
        "name": "gpt-5.1",
        "display_name": "GPT-5.1",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "High-capability GPT-5 variant with excellent reasoning.",
        "context_window": 256000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("12.00"),
        "output_price_per_1m": Decimal("48.00"),
        "sort_order": 2,
    },
    {
        "model_id": "gpt-5-mini",
        "name": "gpt-5-mini",
        "display_name": "GPT-5 Mini",
        "aliases": ["gpt5-mini"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Smaller, faster GPT-5 variant for cost-effective tasks.",
        "context_window": 128000,
        "max_output_tokens": 16384,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("3.00"),
        "output_price_per_1m": Decimal("12.00"),
        "sort_order": 3,
    },
    # GPT-4.5 (Orion)
    {
        "model_id": "gpt-4.5-preview",
        "name": "gpt-4.5-preview",
        "display_name": "GPT-4.5 Preview (Orion)",
        "aliases": ["gpt-4.5", "orion"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Research preview of GPT-4.5 with enhanced capabilities.",
        "context_window": 128000,
        "max_output_tokens": 16384,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("75.00"),
        "output_price_per_1m": Decimal("150.00"),
        "badge": "PREVIEW",
        "sort_order": 5,
    },
    # o-series Reasoning Models
    {
        "model_id": "o3",
        "name": "o3",
        "display_name": "o3 (Reasoning)",
        "aliases": ["o3-reasoning"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.PREMIUM,
        "short_description": "Advanced reasoning model with extended thinking for complex problems.",
        "description": "o3 uses extended thinking to solve complex problems in math, science, and coding. Excels at multi-step reasoning where accuracy is critical. Uses additional tokens for the thinking process.",
        "best_for": ["Mathematical proofs", "Scientific reasoning", "Complex coding", "Logic puzzles", "Research"],
        "limitations": ["Higher latency due to thinking", "Higher cost", "May overthink simple tasks"],
        "context_window": 200000,
        "supports_tools": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("10.00"),
        "output_price_per_1m": Decimal("40.00"),
        "badge": "REASONING",
        "is_featured": True,
        "sort_order": 10,
    },
    {
        "model_id": "o3-pro",
        "name": "o3-pro",
        "display_name": "o3 Pro",
        "category": ModelCategory.REASONING,
        "tier": ModelTier.ENTERPRISE,
        "short_description": "Most intelligent reasoning model for enterprise use.",
        "context_window": 200000,
        "supports_tools": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("20.00"),
        "output_price_per_1m": Decimal("80.00"),
        "badge": "PRO",
        "sort_order": 11,
    },
    {
        "model_id": "o4-mini",
        "name": "o4-mini",
        "display_name": "o4 Mini",
        "aliases": ["o4mini"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.STANDARD,
        "short_description": "Fast, cost-effective reasoning model.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("1.10"),
        "output_price_per_1m": Decimal("4.40"),
        "badge": "FAST",
        "is_featured": True,
        "sort_order": 12,
    },
    # GPT-4.1 Family
    {
        "model_id": "gpt-4.1",
        "name": "gpt-4.1",
        "display_name": "GPT-4.1",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Improved GPT-4 with better instruction following.",
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("2.00"),
        "output_price_per_1m": Decimal("8.00"),
        "sort_order": 20,
    },
    {
        "model_id": "gpt-4.1-mini",
        "name": "gpt-4.1-mini",
        "display_name": "GPT-4.1 Mini",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Smaller GPT-4.1 for everyday tasks.",
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("0.40"),
        "output_price_per_1m": Decimal("1.60"),
        "is_default": True,
        "sort_order": 21,
    },
    # GPT-4o
    {
        "model_id": "gpt-4o",
        "name": "gpt-4o",
        "display_name": "GPT-4o",
        "aliases": ["gpt4o"],
        "category": ModelCategory.MULTIMODAL,
        "tier": ModelTier.STANDARD,
        "short_description": "Multimodal GPT-4 with text, vision, and audio.",
        "context_window": 128000,
        "max_output_tokens": 16384,
        "supports_tools": True,
        "supports_vision": True,
        "supports_audio": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("2.50"),
        "output_price_per_1m": Decimal("10.00"),
        "sort_order": 30,
    },
    {
        "model_id": "gpt-4o-mini",
        "name": "gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "category": ModelCategory.MULTIMODAL,
        "tier": ModelTier.STANDARD,
        "short_description": "Cost-effective multimodal model.",
        "context_window": 128000,
        "max_output_tokens": 16384,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "supports_json_mode": True,
        "input_price_per_1m": Decimal("0.15"),
        "output_price_per_1m": Decimal("0.60"),
        "sort_order": 31,
    },
]


# ==================== Anthropic Models ====================
ANTHROPIC_MODELS: list[dict[str, Any]] = [
    # Claude Opus 4.x
    {
        "model_id": "claude-opus-4-5-20251101",
        "name": "claude-opus-4.5",
        "display_name": "Claude Opus 4.5",
        "aliases": ["claude-opus", "opus-4.5", "opus"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Anthropic's most intelligent model with hybrid extended thinking.",
        "description": "Claude Opus 4.5 represents the pinnacle of Anthropic's model family. Features hybrid extended thinking that can be toggled on for complex reasoning tasks. Exceptional at nuanced analysis, creative writing, and maintaining helpful, harmless responses.",
        "best_for": ["Complex analysis", "Research synthesis", "Nuanced writing", "Ethical reasoning", "Long documents"],
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("15.00"),
        "output_price_per_1m": Decimal("75.00"),
        "badge": "MOST INTELLIGENT",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "claude-opus-4-1-20250805",
        "name": "claude-opus-4.1",
        "display_name": "Claude Opus 4.1",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Previous Opus version with excellent capabilities.",
        "context_window": 200000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("15.00"),
        "output_price_per_1m": Decimal("75.00"),
        "sort_order": 2,
    },
    # Claude Sonnet 4.x
    {
        "model_id": "claude-sonnet-4-5-20250929",
        "name": "claude-sonnet-4.5",
        "display_name": "Claude Sonnet 4.5",
        "aliases": ["claude-sonnet", "sonnet-4.5", "sonnet"],
        "category": ModelCategory.CODING,
        "tier": ModelTier.STANDARD,
        "short_description": "Best coding model with excellent balance of capability and speed.",
        "description": "Claude Sonnet 4.5 is optimized for software development and agentic tasks. Leads benchmarks in code generation, debugging, and understanding complex codebases. Excellent for building AI agents and assistants.",
        "best_for": ["Code generation", "Debugging", "Code review", "AI agents", "Technical writing"],
        "context_window": 200000,
        "max_output_tokens": 16384,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("3.00"),
        "output_price_per_1m": Decimal("15.00"),
        "badge": "BEST FOR CODE",
        "is_featured": True,
        "is_default": True,
        "sort_order": 10,
    },
    {
        "model_id": "claude-sonnet-4-20250514",
        "name": "claude-sonnet-4",
        "display_name": "Claude Sonnet 4",
        "category": ModelCategory.CODING,
        "tier": ModelTier.STANDARD,
        "short_description": "Base Sonnet 4 model for coding tasks.",
        "context_window": 200000,
        "max_output_tokens": 16384,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("3.00"),
        "output_price_per_1m": Decimal("15.00"),
        "sort_order": 11,
    },
    # Claude Haiku 4.x
    {
        "model_id": "claude-haiku-4-5-20251015",
        "name": "claude-haiku-4.5",
        "display_name": "Claude Haiku 4.5",
        "aliases": ["claude-haiku", "haiku"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Fast, cost-effective model for high-volume tasks.",
        "description": "Claude Haiku 4.5 delivers near-frontier intelligence at the most affordable price point. Ideal for high-volume applications requiring quick responses.",
        "best_for": ["Quick responses", "High volume", "Chatbots", "Content moderation", "Summarization"],
        "context_window": 200000,
        "max_output_tokens": 8192,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("0.80"),
        "output_price_per_1m": Decimal("4.00"),
        "badge": "FAST",
        "is_featured": True,
        "sort_order": 20,
    },
    # Claude 3.5 (Legacy but still available)
    {
        "model_id": "claude-3-5-sonnet-20241022",
        "name": "claude-3.5-sonnet",
        "display_name": "Claude 3.5 Sonnet",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Previous generation Sonnet, still excellent for most tasks.",
        "context_window": 200000,
        "max_output_tokens": 8192,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("3.00"),
        "output_price_per_1m": Decimal("15.00"),
        "sort_order": 30,
    },
]


# ==================== Google Models ====================
GOOGLE_MODELS: list[dict[str, Any]] = [
    # Gemini 3.x (2025)
    {
        "model_id": "gemini-3-pro",
        "name": "gemini-3-pro",
        "display_name": "Gemini 3 Pro",
        "aliases": ["gemini-3", "gemini-pro"],
        "category": ModelCategory.MULTIMODAL,
        "tier": ModelTier.PREMIUM,
        "short_description": "#1 on LMArena with exceptional multimodal and reasoning capabilities.",
        "description": "Gemini 3 Pro leads public benchmarks with state-of-the-art performance across text, image, audio, and video understanding. Features native multimodality trained from the ground up.",
        "best_for": ["Multimodal tasks", "Complex reasoning", "Long context", "Research", "Analysis"],
        "context_window": 2000000,
        "max_output_tokens": 65536,
        "supports_tools": True,
        "supports_vision": True,
        "supports_audio": True,
        "supports_video": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("7.00"),
        "output_price_per_1m": Decimal("21.00"),
        "badge": "#1 BENCHMARK",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "gemini-3-deep-think",
        "name": "gemini-3-deep-think",
        "display_name": "Gemini 3 Deep Think",
        "aliases": ["gemini-deep-think"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.PREMIUM,
        "short_description": "Extended thinking mode for complex reasoning tasks.",
        "context_window": 2000000,
        "max_output_tokens": 65536,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("10.00"),
        "output_price_per_1m": Decimal("30.00"),
        "badge": "REASONING",
        "is_featured": True,
        "sort_order": 2,
    },
    {
        "model_id": "gemini-3-flash",
        "name": "gemini-3-flash",
        "display_name": "Gemini 3 Flash",
        "aliases": ["gemini-flash"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Fast, capable model for everyday tasks.",
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("0.15"),
        "output_price_per_1m": Decimal("0.60"),
        "badge": "FAST",
        "is_default": True,
        "sort_order": 3,
    },
    # Gemini 2.5
    {
        "model_id": "gemini-2.5-pro",
        "name": "gemini-2.5-pro",
        "display_name": "Gemini 2.5 Pro",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Stable Gemini model with excellent capabilities.",
        "context_window": 2000000,
        "max_output_tokens": 65536,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("1.25"),
        "output_price_per_1m": Decimal("5.00"),
        "sort_order": 10,
    },
    {
        "model_id": "gemini-2.5-flash",
        "name": "gemini-2.5-flash",
        "display_name": "Gemini 2.5 Flash",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Fast and efficient for high-volume tasks.",
        "context_window": 1000000,
        "max_output_tokens": 32768,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("0.075"),
        "output_price_per_1m": Decimal("0.30"),
        "sort_order": 11,
    },
]


# ==================== Mistral Models ====================
MISTRAL_MODELS: list[dict[str, Any]] = [
    # Mistral Large 3
    {
        "model_id": "mistral-large-3",
        "name": "mistral-large-3",
        "display_name": "Mistral Large 3",
        "aliases": ["mistral-large", "large-3"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Flagship MoE model with frontier capabilities.",
        "description": "Mistral Large 3 uses Mixture of Experts architecture (41B active / 675B total) for efficient high-quality inference. Excellent multilingual support and strong reasoning.",
        "best_for": ["Complex tasks", "Multilingual", "Long context", "Enterprise"],
        "context_window": 256000,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "is_moe": True,
        "parameter_count": "41B active / 675B total",
        "input_price_per_1m": Decimal("2.00"),
        "output_price_per_1m": Decimal("6.00"),
        "badge": "FLAGSHIP",
        "is_featured": True,
        "sort_order": 1,
    },
    # Magistral (Reasoning)
    {
        "model_id": "magistral-medium-1.1",
        "name": "magistral-medium-1.1",
        "display_name": "Magistral Medium 1.1",
        "aliases": ["magistral", "magistral-medium"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.STANDARD,
        "short_description": "Reasoning model with chain-of-thought capabilities.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("2.00"),
        "output_price_per_1m": Decimal("6.00"),
        "badge": "REASONING",
        "is_featured": True,
        "sort_order": 5,
    },
    # Codestral
    {
        "model_id": "codestral-2508",
        "name": "codestral-2508",
        "display_name": "Codestral",
        "aliases": ["codestral"],
        "category": ModelCategory.CODING,
        "tier": ModelTier.STANDARD,
        "short_description": "Specialized model for code generation.",
        "context_window": 32000,
        "supports_tools": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("0.30"),
        "output_price_per_1m": Decimal("0.90"),
        "badge": "CODING",
        "sort_order": 10,
    },
    # Mistral Small
    {
        "model_id": "mistral-small-3.2",
        "name": "mistral-small-3.2",
        "display_name": "Mistral Small 3.2",
        "aliases": ["mistral-small"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Efficient model for everyday tasks.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("0.10"),
        "output_price_per_1m": Decimal("0.30"),
        "is_default": True,
        "sort_order": 20,
    },
]


# ==================== DeepSeek Models (via various providers) ====================
DEEPSEEK_MODELS: list[dict[str, Any]] = [
    {
        "model_id": "deepseek-r1",
        "name": "deepseek-r1",
        "display_name": "DeepSeek R1",
        "aliases": ["r1"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.STANDARD,
        "short_description": "Open-source reasoning model with 94.5% MATH-500 accuracy.",
        "description": "DeepSeek R1 achieves frontier reasoning capabilities through reinforcement learning. Excels at mathematical proofs, scientific reasoning, and complex problem-solving.",
        "best_for": ["Math problems", "Logic puzzles", "Scientific reasoning", "Code reasoning"],
        "limitations": ["No tool/function calling", "English-focused", "May overthink simple tasks"],
        "context_window": 128000,
        "supports_tools": False,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "parameter_count": "671B",
        "input_price_per_1m": Decimal("0.55"),
        "output_price_per_1m": Decimal("2.19"),
        "badge": "OPEN SOURCE",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "deepseek-r1-distill-llama-70b",
        "name": "deepseek-r1-distill-70b",
        "display_name": "DeepSeek R1 Distill 70B",
        "aliases": ["r1-70b", "r1-distill"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.STANDARD,
        "short_description": "Distilled R1 for faster inference.",
        "context_window": 128000,
        "supports_tools": False,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "is_distilled": True,
        "parameter_count": "70B",
        "input_price_per_1m": Decimal("0.59"),
        "output_price_per_1m": Decimal("0.79"),
        "badge": "FAST",
        "sort_order": 2,
    },
    {
        "model_id": "deepseek-v3",
        "name": "deepseek-v3",
        "display_name": "DeepSeek V3",
        "aliases": ["v3"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "General-purpose model with strong capabilities.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("0.27"),
        "output_price_per_1m": Decimal("1.10"),
        "sort_order": 5,
    },
]


# ==================== Llama Models (via various providers) ====================
LLAMA_MODELS: list[dict[str, Any]] = [
    # Llama 4 (2025)
    {
        "model_id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo",
        "name": "llama-4-maverick",
        "display_name": "Llama 4 Maverick",
        "aliases": ["llama-4", "maverick"],
        "category": ModelCategory.MULTIMODAL,
        "tier": ModelTier.STANDARD,
        "short_description": "Meta's flagship open-weight multimodal MoE model.",
        "description": "Llama 4 Maverick is Meta's most capable open-weight model using Mixture of Experts architecture. Native multimodal support for text, images, and video.",
        "best_for": ["General chat", "Multimodal tasks", "Long documents", "Open-source deployment"],
        "context_window": 1000000,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "is_moe": True,
        "parameter_count": "17B active / 400B total",
        "input_price_per_1m": Decimal("0.27"),
        "output_price_per_1m": Decimal("0.85"),
        "badge": "OPEN SOURCE",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "meta-llama/Llama-4-Scout-17B-16E-Instruct-Turbo",
        "name": "llama-4-scout",
        "display_name": "Llama 4 Scout",
        "aliases": ["scout"],
        "category": ModelCategory.MULTIMODAL,
        "tier": ModelTier.STANDARD,
        "short_description": "10 million token context window.",
        "context_window": 10000000,
        "supports_tools": True,
        "supports_vision": True,
        "supports_streaming": True,
        "is_moe": True,
        "parameter_count": "17B active / 109B total",
        "input_price_per_1m": Decimal("0.18"),
        "output_price_per_1m": Decimal("0.59"),
        "badge": "10M CONTEXT",
        "sort_order": 2,
    },
    # Llama 3.3
    {
        "model_id": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "name": "llama-3.3-70b",
        "display_name": "Llama 3.3 70B",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Strong 70B parameter model.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "parameter_count": "70B",
        "input_price_per_1m": Decimal("0.59"),
        "output_price_per_1m": Decimal("0.79"),
        "sort_order": 10,
    },
]


# ==================== Qwen Models ====================
QWEN_MODELS: list[dict[str, Any]] = [
    # Qwen 3 (2025)
    {
        "model_id": "Qwen/Qwen3-235B-A22B-Instruct-Turbo",
        "name": "qwen-3-235b",
        "display_name": "Qwen 3 235B",
        "aliases": ["qwen-3", "qwen3"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Alibaba's flagship MoE model.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "is_moe": True,
        "parameter_count": "22B active / 235B total",
        "input_price_per_1m": Decimal("0.80"),
        "output_price_per_1m": Decimal("0.80"),
        "badge": "FLAGSHIP",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "Qwen/Qwen3-72B-Instruct-Turbo",
        "name": "qwen-3-72b",
        "display_name": "Qwen 3 72B",
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Dense 72B model for complex tasks.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "parameter_count": "72B",
        "input_price_per_1m": Decimal("0.40"),
        "output_price_per_1m": Decimal("0.40"),
        "sort_order": 2,
    },
    # QwQ (Reasoning)
    {
        "model_id": "qwen/qwq-32b-preview",
        "name": "qwq-32b",
        "display_name": "QwQ 32B",
        "aliases": ["qwq"],
        "category": ModelCategory.REASONING,
        "tier": ModelTier.STANDARD,
        "short_description": "Reasoning model with chain-of-thought.",
        "context_window": 32768,
        "supports_tools": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "parameter_count": "32B",
        "input_price_per_1m": Decimal("0.15"),
        "output_price_per_1m": Decimal("0.15"),
        "badge": "REASONING",
        "sort_order": 5,
    },
]


# ==================== Cohere Models ====================
COHERE_MODELS: list[dict[str, Any]] = [
    # Command A (2025)
    {
        "model_id": "command-a-03-2025",
        "name": "command-a",
        "display_name": "Command A",
        "aliases": ["command-a", "command-latest"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.PREMIUM,
        "short_description": "Flagship model with 256K context and native RAG.",
        "description": "Command A is Cohere's most capable model, featuring 111B parameters, native RAG support, and advanced tool use. Optimized for enterprise applications.",
        "best_for": ["RAG applications", "Enterprise search", "Tool use", "Agentic workflows"],
        "context_window": 256000,
        "supports_tools": True,
        "supports_streaming": True,
        "parameter_count": "111B",
        "input_price_per_1m": Decimal("2.50"),
        "output_price_per_1m": Decimal("10.00"),
        "badge": "FLAGSHIP",
        "is_featured": True,
        "sort_order": 1,
    },
    {
        "model_id": "command-a-reasoning",
        "name": "command-a-reasoning",
        "display_name": "Command A Reasoning",
        "category": ModelCategory.REASONING,
        "tier": ModelTier.PREMIUM,
        "short_description": "Extended thinking for complex tasks.",
        "context_window": 256000,
        "supports_tools": True,
        "supports_streaming": True,
        "is_reasoning_model": True,
        "input_price_per_1m": Decimal("3.00"),
        "output_price_per_1m": Decimal("12.00"),
        "badge": "REASONING",
        "sort_order": 2,
    },
    {
        "model_id": "command-r-plus-08-2024",
        "name": "command-r-plus",
        "display_name": "Command R+",
        "aliases": ["command-r-plus"],
        "category": ModelCategory.CHAT,
        "tier": ModelTier.STANDARD,
        "short_description": "Strong RAG and tool use capabilities.",
        "context_window": 128000,
        "supports_tools": True,
        "supports_streaming": True,
        "input_price_per_1m": Decimal("2.50"),
        "output_price_per_1m": Decimal("10.00"),
        "is_default": True,
        "sort_order": 10,
    },
]


# Combine all models by provider
ALL_MODELS_BY_PROVIDER: dict[str, list[dict[str, Any]]] = {
    "openai": OPENAI_MODELS,
    "anthropic": ANTHROPIC_MODELS,
    "google": GOOGLE_MODELS,
    "mistral": MISTRAL_MODELS,
    "cohere": COHERE_MODELS,
    # These are available via multiple providers
    "together": LLAMA_MODELS + QWEN_MODELS + DEEPSEEK_MODELS,
    "groq": [
        {**m, "model_id": m["model_id"].split("/")[-1].lower().replace("-instruct-turbo", "")}
        for m in LLAMA_MODELS[:3]  # Subset for Groq
    ] + DEEPSEEK_MODELS[:2],
    "fireworks": LLAMA_MODELS + QWEN_MODELS[:2] + DEEPSEEK_MODELS,
}
